{% set name = "vica" %}
{% set version = "0.1.6" %}


package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/USDA-ARS-GBRU/vica/archive/v{{ version }}.tar.gz
  sha256: 07eb3ff776f32670acbcdf319348ea102ff708b69f10028974dda35fbb1b5312

  
build:
  number: 0
  entry_points:
    - vica=vica.vica_cli:main
  script: python -m pip install --no-deps --ignore-installed .
  skip: True # [py27]
  script: pip install ete3

requirements:
  host:
    - pip
    - python
  run:
    - pip
    - python
    - tensorflow>=1.4
    - biopython>=1.70
    - pandas>=0.20.3
    - numpy>=1.14
    - scipy>=0.19.0
    - khmer>=2.1.1
    - pyfaidx>=0.5
    - pyyaml
    - scikit-learn>=0.19.0
    - bbmap
    - prodigal

test:
  import:
    - vica
  commands:
    - vica --help

about:
  home: 'https://github.com/USDA-ARS-GBRU/vica'
  license: 'License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication'
  license_family: 'PUBLIC-DOMAIN'
  license_file: ''
  summary: 'Vica: Software to find highly divergent DNA and RNA viruses in microbiomes'


extra:
  recipe-maintainers: 'Adam R. Rivers'
  identifiers:
    - biotools:Vica
    - doi:10.5281/zenodo.1304349
